export const UI_USER_FORM_SUBMITTED = 'UI_USER_FORM_SUBMITTED';
export const STORE_USER_FORM_DATA = 'STORE_USER_FORM_DATA';

export const UI_PRIVACY_FORM_SUBMITTED = 'UI_PRIVACY_FORM_SUBMITTED';
export const STORE_PRIVACY_FORM_DATA = 'STORE_PRIVACY_FORM_DATA';